test releaser path

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -36,6 +36,19 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       
+      - name: Test build
+        continue-on-error: true
+        if: ${{ matrix.binary }} == "lavad"
+        run: |
+          response=$(${{ fromJson(steps.releaser.outputs.artifacts)[0].path }} status --node http://public-rpc.lavanet.xyz:80/rpc/ | jq '.NodeInfo')
+          if [ -z "${response}" ]; then
+            echo "The binary fails to connect to a node."
+            exit 1
+          else
+            echo $response
+            echo "The binary is working as expected."
+          fi
+
       - name: Upload Artifacts
         uses: actions/upload-artifact@v4
         with:
